# Generated by Django 5.0 on 2023-12-19 08:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Point')),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Polygon')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Geo',
                'verbose_name_plural': 'Geos',
            },
        ),
    ]
